version: '3.8'
services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo
    container_name: demo
    environment:
      DATABASE_IP: ${DATABASE_IP}    
    networks:
      - demo
networks:
  demo:
    name: demo-network